server:
  port: 8090

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://mysql:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

  instance:
    prefer-ip-address: true
