server:
  port: 8089

spring:
  application:
    name: recall-service

  datasource:
    url: jdbc:mysql://localhost:3315/recall_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
