server:
  port: 8087

spring:
  application:
    name: spoilage-service

  datasource:
    url: jdbc:mysql://localhost:3313/spoilage_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
